service: web

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-plugin-scripts
  - serverless-domain-manager

build:
  esbuild: true

package:
  patterns:
    - "!app/**"
    - app/build/**

custom:
  customDomain:
    domainName: NA
    certificateArn: ${param:customDomainCertificateARN}
    stage: ""
    endpointType: "regional"
    apiType: http
    autoDomain: true
    enabled: ${param:customDomainNameEnabled}
  scripts:
    hooks:
      # This hook builds the React App. It sets the environment variables for
      # the Chat and Auth APIs and then runs the build script.
      # Use npx to run cross-env, which ensures it's available in the local environment
      "before:esbuild-package:package": "cd website/app && npx cross-env VITE_BUSINESS_API_URL=${param:businessApiUrl} VITE_CHAT_API_URL=${param:chatApiUrl} VITE_AUTH_API_URL=${param:authApiUrl} npm run build"
functions:
  app:
    handler: index.handler
    events:
      - httpApi: "*"
